# This compose will work with docker 1.13.1+
#
# To run, call:
#   $ docker-compose -f cafienne-sqlserver.yml up
#
version: '3.1'
services:
  # supporting containers
  mailcatcher:
    image: schickling/mailcatcher:latest
    labels:
      component: mta
    networks:
      - dev
    expose:
      - 1025
      - 1080
    ports:
      - "1080:1080"
    hostname: mailcatcher
    container_name: mailcatcher
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1080"]
      interval: 30s
      timeout: 10s
      retries: 5

  idp:
    image: quay.io/dexidp/dex:v2.21.0
    command: ["serve", "/config.yaml"]
    networks:
      - dev
    expose:
      - 5556
      - 5558
    ports:
      - "5556:5556"
      - "5558:5558"
    hostname: idp
    container_name: idp
    volumes:
      - ./src/idp-conf/dex.yaml:/config.yaml
      - ./run/dex/:/var/dex/
  
  sql-server:
    image: cafienne/sqlserver:latest
    labels:
      component: cafienne-sql-server
    networks: 
      - dev
    expose:
      - 1433
    ports:
      - "1433:1433"
    hostname: sql-server
    container_name: sql-server
    environment:
      SA_PASSWORD: Abc_123456
      ACCEPT_EULA: Y
      QUERY_DB: cafienneQuery
      EVENT_DB: cafienneEventstore
    volumes:
      - sqlserver-conf-db-data:/var/opt/mssql/data

  cafienne-ide:
    image: cafienne/ide:latest
    labels: 
      component: cafienne-ide
    networks:
      - dev
    expose:
      - 2081
    ports:
      - "2081:2081"
    hostname: ide
    container_name: ide
    environment:
      BACKEND_API_URL: ${BACKEND_API_URL:-http://cafienne:2027}
    volumes:
      - ./target/definitions:/usr/src/app/repository_deploy
      - ./src/definitions:/usr/src/app/repository   
    depends_on:
      - cafienne

  generic-ui:
    image: cafienne/generic-ui:latest
    labels: 
      component: generic-ui
    networks: 
      - dev
    ports:
      - "28080:80"
    hostname: generic-ui
    container_name: generic-ui
    environment:
      NODE_ENV: production
      BACKEND_OIDC_HOST: ${BACKEND_OIDC_HOST:-generic-ui}
      BACKEND_OIDC_PORT: ${BACKEND_OIDC_PORT:-28080}
      BACKEND_DEX_HOST: ${BACKEND_DEX_HOST:-idp}
      BACKEND_DEX_PORT: ${BACKEND_DEX_PORT:-5556}
      BACKEND_API_HOST: ${BACKEND_API_HOST:-cafienne}
      BACKEND_API_PORT: ${BACKEND_API_PORT:-2027}
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:28080/index.html"]
      interval: 30s
      timeout: 10s
      retries: 6
    depends_on:
      - cafienne
      - idp

  cafienne:
    image: cafienne/engine:latest
    labels:
      component: cafienne-engine    
    networks: 
      - dev
    expose:
      - 2027
    ports:
      - "2027:2027"
    hostname: cafienne
    container_name: cafienne
    environment:
      PROJECTION_DB_URL: ${PROJECTION_DB_URL:-jdbc:sqlserver://sql-server:1433;DatabaseName=cafienneQuery;}
      EVENT_DB_URL: ${EVENT_DB_URL:-jdbc:sqlserver://sql-server:1433;DatabaseName=cafienneEventstore;}    
    volumes:
      - ./run/cafienne/journal:/opt/cafienne/journal
      - ./target/definitions:/opt/cafienne/definitions
      - ./src/sqlserver-conf:/opt/cafienne/conf
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - sql-server
      - idp
      - mailcatcher

volumes:
  sqlserver-conf-db-data:
    driver: local
  dex:
    driver: local
networks:
  dev:
    driver: bridge
