# This compose will work with docker 1.13.1+
#
# To run, call:
#   $ docker-compose -f cafienne-demo.yml up
#
version: '3.1'
services:
  # supporting containers
  mailcatcher:
    image: schickling/mailcatcher:latest
    labels:
      component: mta
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1080"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dev
    expose:
      - 1025
      - 1080
    ports:
      - "1080:1080"
    hostname: mailcatcher
    container_name: mailcatcher

  idp:
    image: quay.io/dexidp/dex:v2.21.0
    command: ["serve", "/config.yaml"]
    networks:
      - dev
    expose:
      - 5556
      - 5558
    ports:
      - "5556:5556"
      - "5558:5558"
    hostname: idp
    container_name: idp
    volumes:
      - ./src/idp-conf/dex.yaml:/config.yaml
      - ./run/dex/:/var/dex/

  postgres:
    image: postgres:12.1-alpine
    networks:
      - dev
    expose:
      - 5432
    ports:
      - "5432:5432"
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
    volumes:
      - db-data:/var/lib/postgresql/data      

  cassandra:
    image: cassandra:3.11
    labels:
      component: event-store
    networks:
      - dev
    expose:
      - 9042
    ports:
      - "9042:9042"
    hostname: cassandra
    container_name: cassandra
    volumes:
     - cs-data:/var/lib/cassandra    
    healthcheck:
      test: ["CMD", "cqlsh", "--execute", "show version;quit"]
      interval: 30s
      timeout: 10s
      retries: 5

  cafienne-ide:
    image: cafienne/ide:1.1.0
    labels: 
      component: cafienne-ide
    networks:
      - dev
    expose:
      - 2081
    ports:
      - "2081:2081"
    hostname: ide
    container_name: ide
    environment:
      BACKEND_API_URL: ${BACKEND_API_URL:-http://cafienne:2027}
    volumes:
      - ./target/definitions:/usr/src/app/repository_deploy
      - ./src/definitions:/usr/src/app/repository   
    depends_on:
      - cafienne
    links:
      - cafienne

  generic-ui:
    image: cafienne/generic-ui:1.1.0
    labels: 
      component: generic-ui
    networks: 
      - dev
    ports:
      - "28080:80"
    hostname: generic-ui
    container_name: generic-ui
    environment:
      NODE_ENV: production
      BACKEND_OIDC_HOST: ${BACKEND_OIDC_HOST:-generic-ui}
      BACKEND_OIDC_PORT: ${BACKEND_OIDC_PORT:-28080}
      BACKEND_DEX_HOST: ${BACKEND_DEX_HOST:-idp}
      BACKEND_DEX_PORT: ${BACKEND_DEX_PORT:-5556}
      BACKEND_API_HOST: ${BACKEND_API_HOST:-cafienne}
      BACKEND_API_PORT: ${BACKEND_API_PORT:-2027}
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:28080/index.html"]
      interval: 30s
      timeout: 10s
      retries: 6
    depends_on:
      - cafienne
      - idp
    links:
      - cafienne
      - idp

  cafienne:
    image: cafienne/engine:1.1.0
    labels:
      component: cafienne-engine    
    networks: 
      - dev
    expose:
      - 2027
    ports:
      - "2027:2027"
    hostname: cafienne
    container_name: cafienne
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      CS_HOST: ${CS_HOST:-cassandra}
      PS_HOST: ${PS_HOST:-jdbc:postgresql://postgres:5432/postgresuser}      
    volumes:
      - ./run/cafienne/journal:/opt/cafienne/journal
      - ./target/definitions:/opt/cafienne/definitions
      - ./src/conf:/opt/cafienne/conf
    depends_on:
      - postgres
      - cassandra
      - mailcatcher
    links:
      - cassandra
      - mailcatcher

volumes:
  cs-data:
    driver: local
  db-data:
    driver: local
  dex:
    driver: local
networks:
  dev:
    driver: bridge
