# This compose will work with docker 1.13.1+
#
# To run, call:
#   $ docker-compose -f cafienne-postgres.yml up
#
services:
  # supporting containers
  mailcatcher:
    image: schickling/mailcatcher:latest
    labels:
      component: mta
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://mailcatcher:1080"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - getting_started_network
    expose:
      - 1025
      - 1080
    ports:
      - "1080:1080"
    hostname: mailcatcher
    container_name: mailcatcher

  idp:
    image: quay.io/dexidp/dex:v2.23.0
    command: ["serve", "/dex-setup.yaml"]
    networks:
      - getting_started_network
    expose:
      - 5556
      - 5558
    ports:
      - "5556:5556"
      - "5558:5558"
    hostname: idp
    container_name: idp
    volumes:
      - ./src/dex/conf/dex-setup.yaml:/dex-setup.yaml
      - ./src/dex/web/:/web/
      - ./run/dex/:/var/dex/

  cafienne-db:
    image: postgres:12.1-alpine
    networks:
      - getting_started_network
    expose:
      - 5432
    ports:
      - "5431:5432"
    hostname: cafienne-db
    container_name: cafienne-getting-started-db
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-eventstore
    volumes:
      - ./src/postgres-initdb:/docker-entrypoint-initdb.d
      - cafienne-db-data:/var/lib/postgresql/data

  cafienne-ide:
    image: cafienne/ide:latest
    labels: 
      component: cafienne-ide
    networks:
      - getting_started_network
    expose:
      - 2081
    ports:
      - "2081:2081"
    hostname: ide
    container_name: ide
    environment:
      BACKEND_API_URL: ${BACKEND_API_URL:-http://cafienne:2027}
    volumes:
      - ./target/definitions:/usr/src/app/repository_deploy
      - ./src/definitions:/usr/src/app/repository   
    depends_on:
      - cafienne

  generic-ui:
    image: cafienne/generic-ui:latest
    labels: 
      component: generic-ui
    networks: 
      - getting_started_network
    ports:
      - "28080:80"
    hostname: generic-ui
    container_name: generic-ui
    environment:
      NODE_ENV: production
      BACKEND_OIDC_HOST: ${BACKEND_OIDC_HOST:-generic-ui}
      BACKEND_OIDC_PORT: ${BACKEND_OIDC_PORT:-28080}
      BACKEND_DEX_HOST: ${BACKEND_DEX_HOST:-idp}
      BACKEND_DEX_PORT: ${BACKEND_DEX_PORT:-5556}
      BACKEND_API_HOST: ${BACKEND_API_HOST:-cafienne}
      BACKEND_API_PORT: ${BACKEND_API_PORT:-2027}
    healthcheck:
      test: ["CMD", "curl", "-sS", "-o", "/dev/null", "http://generic-ui/index.html"]
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      - cafienne
      - idp

  cafienne-ui:
    image: cafienne/cafienne-ui:latest
    labels:
      component: cafienne-ui
    networks:
      - getting_started_network
    ports:
      - "3317:80"
    expose:
      - 3317
    hostname: cafienne-ui
    container_name: cafienne-ui
    environment:
      OIDC_URI: ${OIDC_URI:-http://localhost:5556/dex}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-cafienne-ui}
      CAFIENNE_URI: ${CAFIENNE_URI:-http://localhost:2027}
    depends_on:
      - cafienne
      - idp

  cafienne:
    image: cafienne/engine:latest
    labels:
      component: cafienne-engine    
    networks: 
      - getting_started_network
    expose:
      - 2027
    ports:
      - "2027:2027"
    hostname: cafienne
    container_name: cafienne
    healthcheck:
      test: ["CMD", "curl", "-sS", "-o", "/dev/null", "http://cafienne:2027/status"]
      interval: 10s
      timeout: 5s
      retries: 6
    environment:
      EVENT_DB_URL: ${EVENT_DB_URL:-jdbc:postgresql://cafienne-db:5432/cafienne-eventstore?reWriteBatchedInserts=true}    
      EVENT_DB_PROFILE: ${EVENT_DB_PROFILE:-slick.jdbc.PostgresProfile$}
      EVENT_DB_DRIVER: ${EVENT_DB_DRIVER:-org.postgresql.Driver}
      EVENT_DB_USER: ${EVENT_DB_USER:-postgresuser}
      EVENT_DB_PASSWORD: ${EVENT_DB_PASSWORD:-mysecret}
      PROJECTION_DB_PROFILE: ${PROJECTION_DB_PROFILE:-slick.jdbc.PostgresProfile$}
      PROJECTION_DB_DRIVER: ${PROJECTION_DB_DRIVER:-org.postgresql.Driver}
      PROJECTION_DB_USER: ${PROJECTION_DB_USER:-postgresuser}
      PROJECTION_DB_PASSWORD: ${PROJECTION_DB_PASSWORD:-mysecret}
      PROJECTION_DB_URL: ${PROJECTION_DB_URL:-jdbc:postgresql://cafienne-db:5432/cafienne-query?reWriteBatchedInserts=true}
    volumes:
      - ./run/cafienne/journal:/opt/cafienne/journal
      - ./run/cafienne/logs:/opt/cafienne/logs
      - ./target/definitions:/opt/cafienne/definitions
      - ./src/conf:/opt/cafienne/conf
      - ./src/bootstrap:/opt/cafienne/bootstrap
    depends_on:
      - cafienne-db
      - idp
      - mailcatcher

volumes:
  cafienne-db-data:
    driver: local
  dex:
    driver: local
networks:
  getting_started_network:
    driver: bridge
