version: '3.1'
services:
  workspace:
    image: wjgerritsen/cafienne-dev:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/workspaces/getting-started
    ports:
      - 12378
    tty: true           # <- keeps container running
    networks:
      - dev